name: Create Mini-League Chart
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      
    - name: Create Chart
      shell: powershell
      run: |
          cd PowerShell
          cd FPL
          powershell -Command "Import-Module .\PSFPLInfo.psm1"
          cd Tests
          powershell -Command ".\Chart.ps1"
          
