name: Create Mini-League Chart
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      
    - name: Create Chart
      shell: powershell
      run: |
          cd PowerShell
          cd FPL
          powershell -Command Import-Module .\PSFPLInfo.psm1
          powershell -Command $session = Authenticate -username ${{ secrets.FPL_USERNAME }} -password ${{ secrets.FPL_PASSWORD }}; $league = Get-League -leagueId ${{ secrets.FPL_LEAGUE_NUMBER }} -session $session; $chart = Chart -league $league;
