name: ChartCreationTests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Chart Created
      shell: powershell
      run: |
          cd PowerShell
          cd PSFPLInfo
          cd Tests
          powershell -Command ".\CreateChartExists.ps1"
    - name: Correct Login
      shell: powershell
      run: |
          cd PowerShell
          cd PSFPLInfo
          cd Tests
          powershell -Command ".\CreateChartSize.ps1"